name: Deploy

on:
  workflow_run:
    workflows: ["Build"]
    types: [completed]
    branches:
      - main

defaults:
  run:
    working-directory: ./k8s

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Set kubeconfig for Amazon EKS
        run: aws eks update-kubeconfig --region ${{ secrets.AWS_REGION }} --name ${{ secrets.EKS_CLUSTER_NAME }}

      - name: Substitute secrets in ConfigMap
        run: |
          sed -i "s|\${MONGO_DB_CONNECTION_STRING}|${MONGO_DB_CONNECTION_STRING}|g" apptc-configmap.yaml
          sed -i "s|\${MERCADO_PAGO_TOKEN}|${MERCADO_PAGO_TOKEN}|g" apptc-configmap.yaml
        env:
          MONGO_DB_CONNECTION_STRING: ${{ secrets.MONGO_DB_CONNECTION_STRING }}
          MERCADO_PAGO_TOKEN: ${{ secrets.MERCADO_PAGO_TOKEN }}

      - name: Deploy to EKS cluster
        run: |
          chmod +x apptc-apply.sh
          bash apptc-apply.sh
